### ISSUE TITLE
Hi there, I wander if I should replace the OEM nvme ssd (pm981) with other more compatible ssd? 

### ISSUE THREAD

**Issue by Einstonoy** [x1nni/ThinkPad-X1Y3-Monterey#1]
It seems the installation stuck for the incompatibility of hard drive.

**Comment by ejinnis** [comment]
Hi there, I cant comment on compatibility with the OEM SSD as I upgraded to a Samsung 960EVO 1TB NVMe SSD from the stock 256gb one, long before I attempted to hackintosh. You could be correct if your installation is stuck however.

**Comment by Einstonoy** [comment]
Thinks a lot  for you instant reply. Stick to trying now.
