### ISSUE TITLE
Hey man, The power management and related stuff may be solve by "KirisameR / ThinkPad-X1-Yoga-3rd-Hackintosh" Repositories

### ISSUE THREAD

**Issue by Einstonoy** [x1nni/ThinkPad-X1Y3-Monterey#2]
the SMC seems good in this Repositorie.

**Comment by ejinnis** [comment]
I will check it out, and let you know how it goes. Thanks for the suggestion.

**Comment by ejinnis** [comment]
Upon applying the SSDTs in the repo you linked, the power management especially with sleep did not seem to improve at all. That repo is quite old at this point (originally built for Catalina), so I'm not sure that anything from there would be very useful today. Thank you for the suggestion though.
