### ISSUE TITLE
I found shut down became reboot, til I press the power button to operate a hardware shut down.

### ISSUE THREAD

**Issue by Einstonoy** [x1nni/ThinkPad-X1Y3-Monterey#3]

**Comment by ejinnis** [comment]
I have seen this issue myself, but it has been intermittent. Sometimes it will shutdown, other times it will reboot. There may be some BIOS settings related to this, but other than that I am not sure. (Fast Boot, etc.)

**Comment by Einstonoy** [comment]
Yeah, I solved it by turning off fast boot. Everything is fantastically work now! Thanks a lot for you reply!
