### ISSUE TITLE
I wonder if we can add yogamode into this laptop for through use for its special features?

### ISSUE THREAD

**Issue by Einstonoy** [x1nni/ThinkPad-X1Y3-Monterey#4]

**Comment by Einstonoy** [comment]
by the way, multitouch and Wacom pen works great!

**Comment by ejinnis** [comment]
Glad to hear the touch and pen are working. As I mentioned in the README, my screen is cracked and I cannot use the touch or pen, even in Windows. So I am unable to test out any features involving touch or pen. Feel free to try something out on your own and make a pull request.

**Comment by Einstonoy** [comment]
Don't mention it, it makes the efi better!
I add bcm94352z which does not require any drive in config.plist. I recommend use this airport model since everything work perfectly!
